package com.bala;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomProcessEventListener implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CustomProcessEventListener() {
    }




}